# Copyright 2020 Jayson Vibandor. All Right Reserved.

mysql:
  database: gophr
  user: user
  password: mypassword
  host: gophr_database
  port: 3306

gophr:
  port: 8080
  env: PROD
  debug: false

redis:
  address: gophr_redis:6379
  username: ""
  password: ""
  database: 0

debug: true
