# Copyright 2020 Jayson Vibandor. All Right Reserved.

mysql:
  database: gophr_test
  user: testuser
  password: testpassword
  host: 127.0.0.1
  port: 3306

gophr:
  port: 8080
  env: DEV
  debug: false
