version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql.test
    command: mysqld --user=root
    ports:
      - 3306:3306
    volumes:
      - ./deployment/api/integration/gophr.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
    environment:
      - MYSQL_DATABASE=gophr
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
