version: "3.7"
services:
  gophr:
    image: gophr:latest
    ports:
      - 8080:8080
    restart: always
  gophr_database:
    image: mysql:5.7
    container_name: gophr_database
    command: mysqld --user=root
    ports:
      - '3306'
    expose:
      - '3306'
    volumes:
      - ./gophr.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  gophr_redis:
    image: redis:6.0.4
    container_name: gophr_redis
    ports:
      - '6379'
    expose:
      - '6379'
