version: "3.7"
services:
  gophr:
    image: gophr:latest
    container_name: gophr
    environment:
      - GOPHR_ENV=PROD
    ports:
      - 8080:8080
    depends_on:
      - mysql
    volumes:
      - ./config.yaml:/home/config.yaml
      - ./cmd/gophr/assets:/home/gophr/assets
      - ./cmd/gophr/templates:/home/gophr/templates
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root
    ports:
      - 3306:3306
    volumes:
      - ./gophr.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=gophr
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

