version: "3.7"
services:
  gophr:
    image: gophr:latest
    container_name: gophr
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - gophr_database
    environment:
      - GOPHR_ENV=PROD
      - HOME=/home/
    ports:
      - 8080:8080
    depends_on:
      - gophr_database
      - gophr_redis
    volumes:
      - ./config.yaml:/home/.gophr/config.yaml
      - ./cmd/gophr/v2/assets:/home/gophr/v2/assets
      - ./cmd/gophr/v2/templates:/home/gophr/v2/templates
      - ./data:/home/gophr/data
    networks:
      - gophr-backend
    restart: always
  gophr_database:
    image: mysql:5.7
    container_name: gophr_database
    command: mysqld --user=root
    ports:
      - '3306'
    expose:
      - '3306'
    volumes:
      - ./gophr.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=gophr
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - gophr-backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  gophr_redis:
    image: redis:6.0.4
    container_name: gophr_redis
    networks:
      - gophr-backend
    ports:
      - '6379'
    expose:
      - '6379'

# Tutorial: https://linuxhint.com/docker_compose_bridge_networking/
networks:
  gophr-backend:
    name: gophr-backend
    driver: bridge